version: 2.1
orbs:
  python: circleci/python@2.0.3
workflows:
    example-workflow:
      jobs:
        - run:
          name: run tests
          command: |
            . venv/bin/activate
            mkdir test-results
            pytest --junitxml=test-results/junit.xml
        - store_test_results:
          path: test-results

